/**
 * This sketch shows how to segment a sprite sheet generated by ChatGPT
 * and use the frames to create a simple animation.
 *
 * Incidentally: here's the chat for the two spritesheets included
 * in this sketch.
 *
 * https://chatgpt.com/share/690501bb-d790-8010-be38-f4618febaf2b
 **/

const pixelClassify = (() => {
	let rgbaWord = new Uint32Array(1);
	let rgba = new Uint8Array(rgbaWord.buffer);
	const T = 0x12
	return (pixel) => {
		rgbaWord[0] = pixel;
		return rgba[0] > T || rgba[1] > T || rgba[2] > T ? 1 : 0
	}
})();

let sprites, spriteWidth, spriteHeight;
let spriteTexture;
let poly = null;

async function setup() {
	createCanvas(windowWidth, windowHeight, WEBGL);
	pixelDensity(1);
	const spriteSheet = await (loadImage("./chatGptRoseAnimation.png"));
	//const spriteSheet = await (loadImage("./chatGptYellowFlowerAnimation.png"));
	
	({sprites, spriteWidth, spriteHeight} = makeSprites(spriteSheet));
	spriteTexture = makeSpriteTexture(sprites,spriteWidth,spriteHeight);
	//poly = texturedPoly(spriteTexture, sprites.length, 1)

	
}

function makeSpriteTexture(sprites,spriteWidth,spriteHeight) {
	let n = sprites.length;
	let W = spriteWidth*n;
	let fb = createFramebuffer({width:W,height:spriteHeight})
	fb.begin();
	for (let i = 0; i<n; i++) {
		const {img, width:w, height:h} = sprites[i%sprites.length];
		image (img, -W/2+i*spriteWidth,//+(-spriteWidth)/2 + (spriteWidth-w)/2, 
			   (-spriteHeight)/2 + (spriteHeight-h))
	}
	fb.end()
	return fb
}

function componentBoundingBox (runs) {
	let xmin = Infinity, xmax = -Infinity, ymin = Infinity, ymax = -Infinity;
	let area = 0;
	for (let run of runs) {
		xmin = min(xmin, run.x)
		xmax = max(xmax, run.x + run.len)
		ymin = min(ymin, run.y)
		ymax = max(ymax, run.y + 1);
		area += run.len;
	}
	return {x:xmin,y:ymin, width: xmax-xmin,height: ymax-ymin, area}
}

function makeSprites(spriteSheet) {
	let sprites, spriteWidth, spriteHeight;
	spriteSheet.pixelDensity(1)
	spriteSheet.loadPixels();
	let components = imageComponents(spriteSheet.pixels, 
									spriteSheet.width,
									spriteSheet.height,
									pixelClassify);
	
	sprites = [];
	spriteWidth = spriteHeight = 0;
	for (let comp of components) {
		const sprite = componentBoundingBox(comp);
		const {x, y, width:w, height:h} = sprite;
		if ( w < width/4 && w > 5) {
			spriteWidth = max(spriteWidth,w)
			spriteHeight = max(spriteHeight,h);
			sprites.push(sprite)
		}
		else {
			// Make transparent
			paintComponent (spriteSheet.pixels, 
							   spriteSheet.width,
								spriteSheet.height, comp, 0)
		}
	}
	spriteSheet.updatePixels()
	for (let sprite of sprites) {
		let {x,y,width,height} = sprite
		sprite.img = spriteSheet.get(x,y,width,height);
	}
	sprites.sort((a,b)=>a.area-b.area)
	return {sprites, spriteWidth, spriteHeight}
}

function texturedPoly(spriteTexture, n, i) {
	let W = spriteTexture.width;
	let [w,h] = [W/n, spriteTexture.height];
	let ds = w/W;
	function quad() {
		beginShape(QUAD_STRIP);
		vertex(-w/2, -h/2, 0, i*ds, 0);
		vertex(w/2, -h/2, 0, (i+1)*ds, 0)
		vertex(-w/2, h/2, 0, i*ds, 1)
		vertex(w/2, h/2, 0, (i+1)*ds, 1)
		endShape()
	}
	return buildGeometry(quad)
}

function bezierStalk(xbase,ybase,h,bend) {
	let r = h/3
	let ang = -PI/2
	let [x2,y2] = [xbase+r*cos(ang),ybase+r*sin(ang)];
	ang += PI/2*bend;
	let [x3,y3] = [x2+r*cos(ang),y2+r*sin(ang)]
	ang += PI/2*bend;
	let [x4,y4] = [x3+r*cos(ang), y3+r*sin(ang)]
	return [xbase,ybase,x2,y2,x3,y3,x4,y4]
}

function bezierQuad(x1,y1,x2,y2,x3,y3,x4,y4,sz,n, u1, u2) {
	beginShape(QUAD_STRIP)
	let step = 1/(n-1);
	for (let i = 0; i < n; i++) {
		let t = step*i;
		let xs = bezierPoint(x1,x2,x3,x4,t);
		let ys = bezierPoint(y1,y2,y3,y4,t);
		let xtan = bezierTangent(x1,x2,x3,x4,t);
		let ytan = bezierTangent(y1,y2,y3,y4,t);
		let delta = sz/2/Math.hypot(xtan,ytan);
		let xnorm = -ytan*delta;
		let ynorm = xtan*delta;
		vertex (xs+xnorm,ys+ynorm, 0, u1, 1-t)
		vertex (xs-xnorm,ys-ynorm, 0, u2, 1-t)
	}
	endShape()
}

function draw() {
	let bend = map (noise(frameCount/100), 0.2, 0.8, -0.4, 0.4);
	bend += sin(frameCount/3)*0.1
	let cycle = ~~(frameCount/60)
	//if (cycle % 2 == 1) bend = -bend;
	let n = sprites.length;
	let delta = 1/n;
	let [w,h] = [spriteWidth,spriteHeight]
	let u = (cycle % n) * delta;
	let bez = bezierStalk(-w/2, h/2, h, bend);
	let poly1 = buildGeometry(()=> {
		bezierQuad(...bez, w, 8, u, u+delta)
	})
	u = ((cycle+1) % n) * delta;
	let poly2 = buildGeometry(()=> {
		bezierQuad(...bez, w, 8, u, u+delta)
	})
	
	background(0);
	texture (spriteTexture);
	noStroke()
	let alpha = map (frameCount%60, 0, 59, 255, 0);
	for (let j = 0; j < 16; j++) {
		let y = map (j, 0, 15, -height, height*0.1)
		let z = map(j, 0, 15, -2000, 200)
		for (let i = -20; i < 20; i++) {
			push()
			let x = i * w;
			translate(x, y, z)
			tint(255,255)
			model(poly1)
			translate(0,0,1)
			tint(255,255-alpha)
			model(poly2)
			pop()
		}
	}

	freeGeometry(poly1)
	freeGeometry(poly2)
	
}
